local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")

data:extend({
  {
    type = "burner-generator",
    name = "sp-kr-antimatter-reactor",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/antimatter-reactor.png",
    icon_size = 128,
    icon_mipmaps = 4,
    flags = { "placeable-neutral", "placeable-player", "player-creation"},
    minable = { mining_time = 5, result = "sp-kr-antimatter-reactor" },
    max_health = 5000,
    damaged_trigger_effect = hit_effects.entity(),
    corpse = "sp-kr-antimatter-reactor-remnant",
    dying_explosion = "matter-explosion-s",
    effectivity = 5,
    resistances = {
      { type = "physical", percent = 60 },
      { type = "fire", percent = 90 },
      { type = "impact", percent = 90 },
    },
    collision_box = { { -4.75, -4.75 }, { 4.75, 4.75 } },
    selection_box = { { -4.95, -4.95 }, { 4.95, 4.95 } },
    fluid_box = {
      production_type = "input",
      base_area = 1,
      base_level = -1,
      pipe_connections = { {flow_direction="input", direction = defines.direction.south, position = {5, 0}} },
    },
    energy_source = {
      type = "electric",
      render_no_power_icon = false,
      usage_priority = "secondary-output",
    },
    burner = {
      type = "burner",
      fuel_categories = {"sp-kr-antimatter-fuel"},
      fuel_inventory_size = 1,
      burnt_inventory_size = 1,
      effectivity = 1,
      emissions_per_minute = {pollution = 200},
      light_flicker = {
        minimum_intensity = 0.01,
        maximum_intensity = 0.50,
        derivation_change_frequency = 0.02,
        derivation_change_deviation = 0.02,
        minimum_light_size = 1,
        color = { r = 0.459, g = 0.031, b = 0.447 },
      },
    },
    vehicle_impact_sound = sounds.generic_impact,
    -- "burner-generator" do not have graphics_set in factorio 2.0.30
    animation = {
      layers = {
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/antimatter-reactor/antimatter-reactor-light.png",
          priority = "high",
          width = 330,
          height = 353,
          shift = { 0, -0.5 },
          frame_count = 1,
          repeat_count = 30,
          animation_speed = 0.9,
          scale = 0.96,
          draw_as_light = true,
          blend_mode = "additive",
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/antimatter-reactor/antimatter-reactor-glow.png",
          priority = "high",
          width = 330,
          height = 353,
          shift = { 0, -0.5 },
          frame_count = 30,
          line_length = 6,
          -- repeat_count = 30,
          animation_speed = 0.9,
          scale = 0.96,
          blend_mode = "additive-soft",
          draw_as_glow = true,
          fadeout = true,
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/antimatter-reactor/antimatter-reactor.png",
          priority = "high",
          width = 330,
          height = 353,
          shift = { 0, -0.5 },
          frame_count = 30,
          line_length = 6,
          animation_speed = 0.9,
          scale = 0.96,
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/antimatter-reactor/antimatter-reactor-sh.png",
          width = 362,
          height = 315,
          shift = { 0.57, 0.27 },
          frame_count = 1,
          repeat_count = 30,
          animation_speed = 0.9,
          scale = 0.96,
          draw_as_shadow = true,
        },
      },
    },
    working_sound = {
      sound = {
        {
          filename = "__Spaghetorio__/sounds/buildings/antimatter-reactor.ogg",
          volume = 1.25,
        },
      },
    },
    open_sound = { filename = "__Spaghetorio__/sounds/buildings/open.ogg", volume = 1 },
    close_sound = { filename = "__Spaghetorio__/sounds/buildings/close.ogg", volume = 1 },
    audible_distance_modifier = 10,
    min_perceived_performance = 0.25,
    performance_to_sound_speedup = 0.5,
    max_power_output = "3000MW",
  },
})
