data:extend({
  {
    type = "lab",
    name = "sp-biusart-lab",  -- #ForRegEx# - building
    icon = "__Spaghetorio__/graphics/krastorio/icons/entities/biusart-lab.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = { "placeable-player", "player-creation" },
    minable = { mining_time = 0.2, result = "sp-biusart-lab" },
    max_health = 150,
    fast_replaceable_group = "lab",
    corpse = "lab-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    light = {
      intensity = 0.8,
      size = 4,
      color = { r = 255, g = 255, b = 255 },
    },
    -- "lab" do not have graphics_set in factorio 2.0.30
    on_animation = {
      layers = {
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-anim-light.png",
          width = 75 * 2,
          height = 75 * 2,
          frame_count = 29,
          line_length = 10,
          animation_speed = 1 / 3,
          shift = { 0, -0.05 },
          draw_as_light = true,
          scale = 0.64,
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-anim.png",
          width = 75 * 2,
          height = 75 * 2,
          frame_count = 29,
          line_length = 10,
          animation_speed = 1 / 3,
          shift = { 0, -0.05 },
          scale = 0.64,
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-anim.png",
          width = 75 * 2,
          height = 75 * 2,
          frame_count = 29,
          line_length = 10,
          animation_speed = 1 / 3,
          shift = { 0, -0.05 },
          scale = 0.64,
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-anim.png",
          width = 75 * 2,
          height = 75 * 2,
          frame_count = 29,
          line_length = 10,
          animation_speed = 1 / 3,
          shift = { 0, -0.05 },
          scale = 0.64,
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-light-anim.png",
          width = 75 * 2,
          height = 75 * 2,
          frame_count = 29,
          line_length = 10,
          animation_speed = 1 / 3,
          shift = { 0, -0.05 },
          scale = 0.64,
          blend_mode = "additive-soft",
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-light-anim.png",
          width = 75 * 2,
          height = 75 * 2,
          frame_count = 29,
          line_length = 10,
          animation_speed = 1 / 3,
          shift = { 0, -0.05 },
          draw_as_light = true,
          scale = 0.64,
          blend_mode = "additive-soft",
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-shadow.png",
          width = 120 * 2,
          height = 120 * 2,
          frame_count = 1,
          line_length = 1,
          repeat_count = 29,
          animation_speed = 1,
          shift = { 0, -0.20 },
          scale = 0.75,
          draw_as_shadow = true,
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-ao.png",
          width = 110 * 2,
          height = 110 * 2,
          frame_count = 1,
          repeat_count = 29,
          animation_speed = 1 / 3,
          shift = { 0, -0.05 },
          scale = 0.50,
        },
      },
    },
    off_animation = {
      layers = {
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab.png",
          width = 75 * 2,
          height = 75 * 2,
          frame_count = 1,
          shift = { 0, -0.05 },
          scale = 0.64,
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-shadow.png",
          width = 120 * 2,
          height = 120 * 2,
          frame_count = 1,
          repeat_count = 1,
          shift = { 0, -0.20 },
          scale = 0.75,
          draw_as_shadow = true,
        },
        {
          filename = "__Spaghetorio__/graphics/krastorio/entities/biusart-lab/hr-biusart-lab-ao.png",
          width = 110 * 2,
          height = 110 * 2,
          frame_count = 1,
          repeat_count = 1,
          animation_speed = 1 / 3,
          shift = { 0, -0.05 },
          scale = 0.5,
        },
      },
    },
    working_sound = {
      sound = {
        filename = "__Spaghetorio__/sounds/buildings/biusart-lab.ogg",
        volume = 0.7,
      },
      apparent_volume = 1,
    },
    vehicle_impact_sound = {
      filename = "__base__/sound/car-metal-impact.ogg",
      volume = 0.65,
    },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
    },
    energy_usage = "250kW",
    researching_speed = 1,
    inputs = {
      "automation-science-pack",
      "logistic-science-pack",
      "military-science-pack",
      "chemical-science-pack",
      "sp-geological-science-pack-1",
      "sp-material-science-pack-1",
      "sp-electronic-science-pack-1",

      "sp-automation-science-pack-2",
      "sp-logistic-science-pack-2",
      "sp-military-science-pack-2",
      "sp-chemical-science-pack-2",
      "sp-electronic-science-pack-2",
      "sp-geological-science-pack-2",
      "sp-material-science-pack-2",
      "sp-metallurgic-science-pack-2",
      "sp-electromagnetic-science-pack-2",
      "sp-computer-science-pack-2",
      "sp-nuclear-science-pack-2",
      "production-science-pack",
      "utility-science-pack",
      "space-science-pack",

      -- "sp-automation-science-pack-3",
      -- "sp-logistic-science-pack-3",
      -- "sp-military-science-pack-3",
      -- "sp-chemical-science-pack-3",
      -- "sp-electronic-science-pack-3",
      -- "sp-geological-science-pack-3",
      -- "sp-material-science-pack-3",
      -- "sp-metallurgic-science-pack-3",
      -- "sp-electromagnetic-science-pack-3",
      -- "sp-biological-science-pack-3",
      -- "sp-cryogenic-science-pack-3",
      -- "sp-computer-science-pack-3",
      -- "sp-production-science-pack-3",
      -- "sp-nuclear-science-pack-3",
      -- "sp-utility-science-pack-3",
      -- "sp-space-science-pack-3",
      -- "sp-matter-science-pack",

      -- "space-science-pack",  -- Optimization tech card
      -- "sp-advanced-science-pack",
      -- "sp-singularity-science-pack",
      -- "sp-uniformity-science-pack",

      "agricultural-science-pack",
      "electromagnetic-science-pack",
      "metallurgic-science-pack",
      "cryogenic-science-pack",
      -- "promethium-science-pack",
    },
    module_slots = 3,
    icons_positioning = {
      {inventory_index = defines.inventory.lab_modules, shift = {0, 0.9}},
      {inventory_index = defines.inventory.lab_input, shift = {0, -0.5}, max_icons_per_row = 8, separation_multiplier = 1/1.1, scale = 0.3}
    },
  },
})
